export const wordList:string[] = [
    "apple","tanana", "banana", "cat", "dog", "elephant", "flower","garden", "house", "ice cream", "jump",
    "kite", "lemon", "mountain", "nest", "orange", "piano", "quilt", "rainbow", "sun", "tree",
    "umbrella", "violin", "watermelon", "xylophone", "yellow", "zebra", "actor", "bicycle", "chocolate",
    "dancer", "eagle", "forest", "guitar", "hat", "island", "jigsaw", "kangaroo", "library", "mango",
    "notebook", "ocean", "popcorn", "queen", "rocket", "soccer", "telescope", "unicorn", "volcano",
    "wizard", "yogurt", "aeroplane", "balloon", "cucumber", "dolphin", "envelope", "fountain", "giraffe",
    "honey", "igloo", "jacket", "kaleidoscope", "lighthouse", "moon", "ninja", "octopus", "pirate",
    "puzzle", "quill", "rocket", "spaceship", "telescope", "universe", "victory", "waterfall", "xylograph",
    "yearbook", "zeppelin", "adventure", "backpack", "curiosity", "dragonfly", "enchanted", "festival",
    "galaxy", "harmony", "invisible", "jamboree", "kindness", "laughter", "meadow", "nocturnal", "onyx",
    "playground", "quasar", "radiant", "serendipity", "tranquility", "utopia", "voyage", "whimsical",
    "xenon", "yodel", "zest", "abracadabra", "babble", "cacophony", "doodle", "effervescent", "flabbergast",
    "galumph", "hodgepodge", "imbroglio", "jambalaya", "kerfuffle", "lollygag", "mollycoddle", "namaste",
    "oodles", "pandemonium", "quizzical", "rambunctious", "skedaddle", "topsy-turvy", "ukulele", "voluble",
    "whimsy", "xenial", "yo-yo", "zephyr", "acumen", "brouhaha", "cantankerous", "discombobulate", "ephemeral",
    "facetious", "gargantuan", "haphazard", "idyllic", "juxtapose", "kowtow", "lugubrious", "mellifluous",
    "nefarious", "obfuscate", "perspicacious", "quixotic", "rambunctious", "salubrious", "tantamount", "ubiquitous",
    "verisimilitude", "wunderkind", "xenophobe", "yokel", "zenith", "antediluvian", "bilious", "chicanery", "debonair",
    "effulgent", "farrago", "gambol", "halcyon", "ineffable", "juxtapose", "knell", "lagniappe", "mellifluous", "nadir",
    "obfuscate", "peregrinate", "quizzical", "redolent", "serendipity", "tempestuous", "ubiquitous", "vernacular", "winsome",
    "xenial", "yare", "zealot", "alacrity", "beguile", "capricious", "dalliance", "ephemeral", "furtive", "gossamer",
    "harangue", "impervious", "jejune", "kowtow", "loquacious", "maverick", "nebulous", "obstreperous", "palliate",
    "quiescent", "recalcitrant", "sagacious", "taciturn", "ubiquitous", "vacillate", "wily", "xenophobe", "yare", "zenith",
    "acumen", "bedazzle", "cacophony", "demure", "ebullient"
  ];
  